baseURL = "https://www.replicated.com/docs/"
languageCode = "en-us"
title = "Replicated Documentation"
theme = "hugo-material-docs"
canonifyURLs = true
googleAnalytics = "UA-61084834-1"
pygmentsCodeFences = true
pygmentsUseClasses = true
copyright = "Replicated, Inc."

[taxonomies]
category = "categories"

[params]
  description = "Documentation and knowledgebase for Replicated."

  logo = "images/logo.png"
  favicon = ""
  pagetitle = "Replicated"
  permalink = "#"

  # Custom assets
  custom_css = []
  custom_js  = []

  # Syntax highlighting theme
  highlight_css  = ""

  docker_version_default = "17.03.1-ce"
  docker_version_minimum = "1.7.1"
  replicated_api_version_current = "2.9.0"
  replicated_latest_version = "2.9.0"
  replicated_latest_release_date = "June 14, 2017"

  swarm_docker_version_minimum = "1.13.1"
  swarm_docker_version_default = "17.03.1-ce"

  [params.palette]
  primary = "red"
  accent  = "light green"

  [params.font]
  text = "Ubuntu"
  code = "Ubuntu Mono"

[social]
  twitter = ""

[[menu.main]]
  name       = "Getting Started"
  url        = "getting-started"
  identifier = "/getting-started"
  weight     = 100

[[menu.main]]
  name       = "Packaging An Application"
  url        = "packaging-an-application"
  identifier = "/packaging-an-application"
  weight     = 200

[[menu.main]]
  name       = "Distributing An Application"
  url        = "distributing-an-application"
  identifier = "/distributing-an-application"
  weight     = 300

[[menu.main]]
  name       = "Examples"
  url        = "examples"
  identifier = "/examples"
  weight     = 400

[[menu.main]]
  name       = "Reference"
  url        = "reference"
  identifier = "/reference"
  weight     = 500

[[menu.main]]
  name       = "Knowledge Base"
  url        = "kb"
  identifier = "/kb"
  weight     = 600

[blackfriday]
  smartypants	= true
  fractions = true
  smartDashes = true
  plainIDAnchors = true
